[Setting]
spotify_path           = /nix/store/ki7nn8j53xjhq1bjx6hgclaf3n8yqbbh-spotify-1.2.31.1205.g4d59ad7c/
color_scheme           = Base
overwrite_assets       = 0
spotify_launch_flags   = 
always_enable_devtools = 0
prefs_path             = /home/stamno/.config/spotify/prefs
current_theme          = Everblush
inject_theme_js        = 1
inject_css             = 1
replace_colors         = 1
check_spicetify_update = 1

[Preprocesses]
disable_sentry     = 1
disable_ui_logging = 1
remove_rtl_rule    = 1
expose_apis        = 1

[AdditionalOptions]
home_config           = 1
experimental_features = 1
extensions            = 
custom_apps           = 
sidebar_config        = 1

[Patch]

; DO NOT CHANGE!
[Backup]
version = 
with    = 
