#! /bin/sh

$HOME/.config/polybar/launch.sh
feh --bg-fill -- /home/stamno/Pic/wallpaper.png
pgrep -x sxhkd > /dev/null || sxhkd &
picom &

bspc monitor -d один два три четыре

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a brave desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Emacs state=tiling
