#! /bin/sh

$HOME/.config/polybar/launch.sh
autorandr -c
feh --bg-fill /home/stamno/Pics/Wallpapers/bacground1.png
pgrep -x sxhkd > /dev/null || sxhkd &
picom --experimental-backends -b &
#setxkbmap dvorak &

#bspc monitor DP-0 -d один два три четыре пять
#bspc monitor HDMI-0 -d шесть семь восемь девять десять
bspc monitor DP-0 -d 1 2 3 4 5
bspc monitor HDMI-0 -d 6 7 8 9 10

bspc config border_width 6
bspc config window_gap 0
bspc config focused_border_color "#d3869b"
bspc config normal_border_color "#ebdbb2"


bspc config split_ratio          0.60
bspc config borderless_monocle   true
bspc config gapless_monocle      false

bspc rule -a Gimp desktop='^8' state=floating follow=on 
bspc rule -a Brave-browser desktop='^13' state=tiled
bspc rule -a mpv desktop='^0'
bspc rule -a Kupfer.py focus=on 
bspc rule -a Screenkey manage=off 
bspc rule -a Emacs  state=tiled
bspc rule -a Zathura state=tiled
bspc rule -a Steam state=floating
